version: '3.8'


services:
  cinema_db:
    image: postgres:latest
    container_name: cinema_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: cinema
      POSTGRES_DB: cinema
    ports:
      - "5432:5432"  # Пробрасываем порт 5432
    volumes:
      - cinema_data:/var/lib/postgresql/data  # Для хранения данных
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d cinema"]
      interval: 30s
      timeout: 10s
      retries: 5

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: minioadmin # change it!!!!
      MINIO_ROOT_PASSWORD: minioadmin # change it!!!!
    command: server --console-address ":9001" /data
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  cinema_data:
  minio_storage: {}
